# Configuration for secret scanning alerts

# Action to be taken when a secret is detected
action: audit

# If we need to disable specific alerts, add the pattern to the below array
# This is NOT recommended!
disabledPatterns:
